import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "@/components/ui/toaster";
import SessionAccesser from "@/components/widgets/SessionAccessor";
import { Theme } from "@radix-ui/themes";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Wordle Clone",
  description: "Generated by create next app",
};


export default function FormLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Theme appearance="dark">
    <section className="flex justify-center items-center">
      <SessionAccesser>
        
        
        {children}
       
        
        <Toaster />
      </SessionAccesser>
    </section>
    </Theme>
  
);
}
