import type { Metadata } from "next";
import { Special_Elite } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import SessionAccesser from "@/components/widgets/SessionAccessor";
import Navbar from "@/components/widgets/Navbar";

const specialElite = Special_Elite({
  weight: "400",
  style: "normal",
  preload: false
});

export const metadata: Metadata = {
  title: "Wordle Clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${specialElite.className} bg-background`}>
        <SessionAccesser>
          <Navbar />
          
          {children}
         
          
          <Toaster />
        </SessionAccesser>
      </body>
    </html>
  );
}
